version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: estadisticas
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app     # ← HOT RELOAD: tu código
    command: uvicorn backend.controller.fastapi:app --reload --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/estadisticas
      - USUARIOS_API_BASE_URL=http://host.docker.internal:3000/api/usuarios
      - MS_USUARIOS_BASE_URL=http://host.docker.internal:3000
      - MS_CONTENIDO_BASE_URL=http://host.docker.internal:8083/api
      - MS_COMUNIDAD_BASE_URL=http://host.docker.internal:8084

volumes:
  postgres_data:
